name: build XNU22 Hypervisor
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: Build XNU22(iOS16) Hypervisor
        required: false
        default: false
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: utmapp/Hypervisor
          path: './Hypervisor'
      - name: Build
        run: |
          cd Hypervisor
          xcodebuild archive -archivePath "Hypervisor" -scheme "Hypervisor" -sdk iphoneos -configuration Release
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Hypervisor.framework
          path: Hypervisor/Hypervisor.xcarchive/Products/Library/Frameworks/Hypervisor.framework/
